version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    network_mode: "host"  # Use host networking
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--web.listen-address=:6970'
    ports:
      - "6970:6970"
    restart: unless-stopped
    
  grafana:
    image: grafana/grafana
    network_mode: "host"  # Use host networking
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/validator_dashboard.json:/etc/grafana/dashboards/validator_dashboard.json
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_SERVER_HTTP_PORT: "6971"
      GF_FEATURE_TOGGLES_ENABLE: "publicDashboards"
      GF_PUBLIC_DASHBOARDS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_AUTH_BASIC_ENABLED: "true"
      GF_INSTALL_PLUGINS: ""
      GF_LOG_LEVEL: "debug"
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana-storage: