global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'validator'
    static_configs:
      - targets: ['localhost:6969']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true